### PR TITLE
django-admin-tools integration - ControlCenterMenu implemented

### PR DESCRIPTION
**Pull request by daadu**
I have filled this feature request  #49 for integrating controlcenter with django-admin-tools.

I anyways was doing it for my project thought  adding it to this project would be worthwhile.

This is my first PR on github so forgive me if I have made any mistakes.

### CODE REVIEW

**Comment by daadu** [comment]
I can see an issue with code coverage, I am afraid I am not equipped with writing a test.

**Comment by daadu** [comment]
I this is merged i can also work for a ControlCenterModule that will show all dashboards in django-admin-tools Dashboard

**Comment by byashimov** [comment]
Hi 👋 Thanks for your request. I'll take a closer look on weekends!

**Comment by daadu** [comment]
Any update?

**Comment by byashimov** [comment]
Hi. Could you provide some tests?

**Comment by daadu** [comment]
I don't know how to write tests

**Pull request closed without merging**
