### PR TITLE
Add DashboardBaseView

### PR DESCRIPTION
**Pull request by iterq1**
Add common view for dashboards to inherit from and create an unlimited number of dashboards at different urls.

### CODE REVIEW

**Comment by byashimov** [comment]
Hi!
Thank you for collaborating !
I'm not really sure about the design you have suggested, because it looks like it should stack in [here](https://github.com/byashimov/django-controlcenter/blob/master/controlcenter/dashboards.py#L39), but since you haven't provided any tests I can't say it does.
When you call `Dashboard.get_absolute_url`, `reverse` looks up for `'controlcenter:dashboard'` which limits dashboards to 10 and this is the part you want to be fixed:
```python
# Limits number to 10
length = min([len(self.dashboards) - 1, 9])
values = length and '[0-{}]'.format(length)
urlpatterns = [
    url(r'^(?P<pk>{})/$'.format(values), dashboard_view,
        name='dashboard'),
]
```
I thought 10 dashes is just fine, because if you need more, you should have a screen is wide enough to fit all that tabs in a row. Also fitting more 'pages' makes regex a bit more complex and uglier than `[0-9]`. Try to figure out one for 11 dashes.
If you really need more dashboards, I will replace that part to handle more values.
P.S. Please take a look at [this](https://github.com/django/django/blob/master/.gitignore) comment about extending `.gitignore`, you might find it useful.

**Comment by byashimov** [comment]
Hi!
Checkout developer branch for unlimited dashboards support https://github.com/byashimov/django-controlcenter/tree/develop

**Comment by iterq1** [comment]
Hi! Sorry, I wanted to reply earlier, but couldn't.

I think I described my purpose not precise enough.
What I want to get is more flexible way to create urls for dashboard.
For example, I have a case when I need a separate dashboard page for every User with data & stats related to it. So I would like to have urls like `.../dashboards/users/(?P<pk>\d+)`. 

And it seems to me that the best way to achieve this is to use your own url-patterns and own view class inherited from some base class for all dashboards. Or perhaps I don't see an easier way? :)

**Comment by byashimov** [comment]
Yeah... It's commonly expected the _only_ url for the model.
Then you don't need to modify the app:
```python
# your root urls fil
from controlcenter.views import controlcenter, dashboard_view
# init the app
controlcenter.get_urls()
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # support first one
    url(r'^admin/myurl/(?P<pk>0)/$', dashboard_view, name='mydashboard'),
    # support other
    url(r'^admin/mysecondurl/(?P<pk>[1-2])/$', dashboard_view, name='myseconddashboard'),
    ...
]

# your dashboard file
class MyDashboard(Dashboard):
    def get_absolute_url(self):
        return reverse('mydashboard', kwargs={'pk': self.pk})

class MySecondDashboard(Dashboard):
    def get_absolute_url(self):
        return reverse('myseconddashboard', kwargs={'pk': self.pk})

class MyOtherDashboard(MySecondDashboard):
    pass
```
Then just place them in the order to your settings file.

**Comment by iterq1** [comment]
Yes, it works :) Thanks!

**Pull request closed without merging**
