### PR TITLE
Setup test job github workflows

### PR DESCRIPTION
**Pull request by mick88**
Test to run against every combination of supported version of Python and django

### CODE REVIEW

**Comment by mick88** [comment]
I saw your comment about Travis CI not working for you any more. Here's a copy of github actions setup from my fork.

**Comment by mick88** [comment]
tests are failing due to incompatibilities with newer versions of django. I'll push some more commits to fix them

**Comment by byashimov** [comment]
Thanks a lot!

**Comment by byashimov** [comment]
New version has just been uploaded. I would appreciate for your feedback. Thanks!

**Pull request merged**
