### PR TITLE
show sorting triangles

### PR DESCRIPTION
**Pull request by minusf**
My users find the sorting gradient a bit too subtle, I think the triangles make it much easier to see what's going on. CSS taken from sortable's minimal css.

### CODE REVIEW

**Comment by byashimov** [comment]
Could you provide screenshots with changes (then, now). I have no chance to check this on my own.

**Comment by minusf** [comment]
no triangles:
screenshot 2019-01-21 at 13 20 18
screenshot 2019-01-21 at 13 20 26


triangles:
screenshot 2019-01-21 at 13 16 43
screenshot 2019-01-21 at 13 16 49

**Comment by minusf** [comment]
as you can see, `all.css` is getting the same changes from the grunt job as in my other PR.  perhaps you can just accept the `all.styl` changes and generate `all.css` yourself?

**Comment by byashimov** [comment]
Thanks for a screenshot. Please, take a look at another request with dropped css style (subtitle class).

**Comment by minusf** [comment]
what would you like me to do?  send just the `all.styl` change and you will generate and commit `all.css`?

```
$ node_modules/.bin/stylus  -V
0.54.5
$ node_modules/.bin/grunt  -V 
grunt-cli v1.2.0
grunt v1.0.3
```

**Comment by byashimov** [comment]
F*k. Sounds like changes was made in css directly (not in styl). So when you regenerate new css it drops unknown class. I will have to fix css after your merge.

**Pull request merged**
